version: '3'

services:
    postgres:
        image: postgres:14
        restart: on-failure:5
        ports:
            - 5432:5432
        volumes:
            - ./db_data:/var/lib/postgresql/data
        env_file:
            - config/.env 
        